# Generated by Django 4.1.4 on 2023-09-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=105, null=True)),
                ('email', models.CharField(blank=True, max_length=105, null=True)),
                ('number', models.CharField(blank=True, max_length=105, null=True)),
                ('DOB', models.CharField(blank=True, max_length=105, null=True)),
                ('city', models.CharField(blank=True, max_length=105, null=True)),
                ('pin', models.CharField(blank=True, max_length=105, null=True)),
            ],
        ),
    ]
