# Generated by Django 4.1.4 on 2023-09-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TableApp', '0002_alter_employee_dob_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='DOB',
            new_name='dob',
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
