# Generated by Django 4.1.4 on 2023-09-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0002_registration_name_registration_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
