# Generated by Django 4.1.4 on 2023-09-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='discription',
            field=models.TextField(),
        ),
    ]
