# Generated by Django 4.1.4 on 2023-09-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0006_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Sliders/')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('Description', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_save_time', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='short_description',
        ),
    ]
